### ISSUE TITLE
Form with error not showing selected conditional content

### ISSUE THREAD

**Issue by nunommc** [nhsuk/nhsuk-frontend#608] opened 2020-05-19 13:18 UTC
# Bug Report

## What is the issue?
Please watch [this video](https://www.loom.com/share/aed69d8ef8fd4a799bce794633d3cbe9) for details.

When a form is submitted
And the validations are not fulfilled
The form is re-rendered with errors

However, the conditional content previously displayed is now hidden and the user will not easily find the error in the form.

Expected to show the conditional content on page load.

**Comment by tomdoughty** [comment] 2020-05-19 14:00
Hi Nuno,

Are you using the Nunjucks template or the HTML component? I am unable to replicate the issue using Nunjucks. If using HTML you will need to ensure you have handled the setting of classes and IDs manually for the functionality to work.

Also the general layout looks like it will may have accessibility issues caused by nesting fieldsets.

Thanks, Tom

**Comment by nunommc** [comment] 2020-05-19 22:29
We're using https://github.com/DFE-Digital/govuk_design_system_formbuilder to generate the HTML for this form. This gem takes care of the classes and IDs and all is working fine in regards to using the conditional. The only issue is when the page is rendered in a state when the content should be expanded but it's not.

**Comment by davidhunter08** [comment] 2020-05-20 08:19
Hey @nunommc,

The conditional content guidance does say:

> Keep it simple. If you need to add a lot of content, consider showing it on the next page in the process instead.

Also, (like Tom mentioned) having a fieldset within a fieldset is an accessibility issue. See the ['Using fieldset and legend' blog post](https://accessibility.blog.gov.uk/2016/07/22/using-the-fieldset-and-legend-elements/).

> It is possible to nest one <fieldset> element inside another, but it is not recommended. Screen readers do not automatically indicate the end of the <fieldset> element, so it is impossible for screen reader users to confidently know which fields belong within which fieldset.

Have you considered making the Yes/No question a '[filter question](https://service-manual.nhs.uk/content/how-to-write-good-questions-for-forms/use-filter-questions-to-route-users)' and using the ['one thing per page principle'](https://service-manual.nhs.uk/content/how-to-write-good-questions-for-forms/get-the-questions-into-order)?

So the "When did your symptoms start?" and "Which symptoms have you experienced?" questions would be on separate pages.

This would fix your issue and also simplify the interaction by giving users only:
- 1 question to answer
- 1 decision they have to make

I hope this helps.

**Comment by tomdoughty** [comment] 2020-05-20 08:24
Hi Nuno,

As far as I can see in the documentation the [form builder](https://github.com/DFE-Digital/govuk_design_system_formbuilder) is not made to work with NHS.UK Frontend. Any work needed to make it work would need to be in the form builder codebase.

NHS.UK Frontend cannot be switched like for like with GOV.UK Design System. Since NHS.UK was created as a fork of GOV.UK both libraries have grown in their own ways to address their own user needs.

**Comment by WorkSutton** [comment] 2020-05-20 09:53
Hi @tomdoughty - there is a beta version of the [Beta form builder for CTAS project](https://github.com/DFE-Digital/govuk_design_system_formbuilder/releases/tag/v1.2.0b2) which was adapted by Peter Yates. 
Was this the version you were looking at?

**Comment by WorkSutton** [comment] 2020-05-20 09:55
> Hey @nunommc,
> 
> The conditional content guidance does say:
> 
> > Keep it simple. If you need to add a lot of content, consider showing it on the next page in the process instead.
> 
> Also, (like Tom mentioned) having a fieldset within a fieldset is an accessibility issue. See the ['Using the fieldset and legend elements' blog post](https://accessibility.blog.gov.uk/2016/07/22/using-the-fieldset-and-legend-elements/).
> 
> > It is possible to nest one fieldset element inside another, but it is not recommended. Screen readers do not automatically indicate the end of the fieldset element, so it is impossible for screen reader users to confidently know which fields belong within which fieldset.
> 
> Have you considered making the Yes/No question a '[filter question](https://service-manual.nhs.uk/content/how-to-write-good-questions-for-forms/use-filter-questions-to-route-users)' and using the ['one thing per page principle'](https://service-manual.nhs.uk/content/how-to-write-good-questions-for-forms/get-the-questions-into-order)?
> 
> So the "When did your symptoms start?" and "Which symptoms have you experienced?" questions would be on separate pages.
> 
> This would fix your issue and also simplify the interaction by giving users only:
> 
> * 1 question to answer
> * 1 decision they have to make
> 
> I hope this helps.

@davidhunter08 I have addressed your suggestion around accessibility with a colleague who is focused on this area. Thank you.

**Comment by tomdoughty** [comment] 2020-05-20 10:45
> Hi @tomdoughty - there is a beta version of the [Beta form builder for CTAS project](https://github.com/DFE-Digital/govuk_design_system_formbuilder/releases/tag/v1.2.0b2) which was adapted by Peter Yates.
> Was this the version you were looking at?

Hi @WorkSutton 
It wasn't but now from what I can see (maybe wrong as I haven't really got much experience with Ruby) it looks like it is relying on the markup and JavaScript of NHS.UK and GOV.UK design systems being the same.
If the app used the latest markup and JavaScript from NHS.UK Frontend then the issue should not occur.

**Comment by AdamChrimes** [comment] 2020-05-26 13:44
This looks like it could be a potential issue with the way the form is being put together, it's expected that users write their own logic for error messages and error summaries, this would also be the case to display the conditional reveals on error.

It seems this is being picked up as part of the form builder repo - are we happy to close this issue?

**Closed** 2020-06-02 09:14 UTC
