### ISSUE TITLE
Text input and text area adjusting when focused

### ISSUE THREAD

**Issue by Fenwick17** [nhsuk/nhsuk-frontend#613] opened 2020-07-06 13:10 UTC
# Bug Report

## What is the issue?

When an `<input type="text" />` or `<textarea>` receives focus, there is a slight sizing adjustment due to how we handle the yellow focus state with `box-shadow`.
This can be seen when adding a `placeholder` on the text input component https://service-manual.nhs.uk/design-system/components/text-input
The text area component does the same as well as adjusting the preview box in the service manual https://service-manual.nhs.uk/design-system/components/textarea

## What steps are required to reproduce the issue?

Add a placeholder to either elements and apply focus

## What was the environment where this issue occurred?

* Device: Macbook
* Operating System: Catalina
* Browser: Google Chrome/Firefox
* Browser version: Latest
* NHS.UK frontend package version: 3.1.0

## Solution

As the focus state is based on the one used by gov.uk we should follow their method, and apply the focus state using `outline` rather than `box-shadow` 
https://design-system.service.gov.uk/components/text-input/

**Comment by tomdoughty** [comment] 2020-07-06 13:14
Partical duplicate of #600

**Comment by davidhunter08** [comment] 2020-07-06 13:16
Do you want to go ahead fix this @Fenwick17?

**Comment by Fenwick17** [comment] 2020-07-07 08:20
@davidhunter08 Yeah I will take a look and get it sorted, as Tom pointed out it should also resolve #600

**Closed** 2020-09-30 16:27 UTC
Labels: :clock10: days, Priority: low, component
